### ISSUE TITLE
this appears to be a great sample, but it does not build

### ISSUE THREAD

**Issue by mschulz531** [Azure-Samples/powerbi-dotnet-server-aspnet-web-api#1]
Severity    Code    Description Project File    Line    Suppression State
Error   CS0234  The type or namespace name 'Models' does not exist in the namespace 'Microsoft.PowerBI.Api' (are you missing an assembly reference?)    PbiPaasWebApi   C:\SampleCode\pbi-web-api\PbiPaasWebApi\Models\ReportWithToken.cs   1   Active
Error   CS0103  The name 'PowerBIToken' does not exist in the current context   PbiPaasWebApi   C:\SampleCode\pbi-web-api\PbiPaasWebApi\Controllers\ReportsController.cs    36  Active
Error   CS0103  The name 'PowerBIToken' does not exist in the current context   PbiPaasWebApi   C:\SampleCode\pbi-web-api\PbiPaasWebApi\Controllers\ReportsController.cs    46  Active
Error   CS0103  The name 'PowerBIToken' does not exist in the current context   PbiPaasWebApi   C:\SampleCode\pbi-web-api\PbiPaasWebApi\Controllers\ReportsController.cs    62  Active
Error   CS0103  The name 'PowerBIToken' does not exist in the current context   PbiPaasWebApi   C:\SampleCode\pbi-web-api\PbiPaasWebApi\Controllers\ReportsController.cs    72  Active
Error   CS0103  The name 'PowerBIToken' does not exist in the current context   PbiPaasWebApi   C:\SampleCode\pbi-web-api\PbiPaasWebApi\Controllers\ReportsController.cs    88  Active
Error   CS0103  The name 'PowerBIToken' does not exist in the current context   PbiPaasWebApi   C:\SampleCode\pbi-web-api\PbiPaasWebApi\Controllers\ReportsController.cs    100 Active
Error   CS0246  The type or namespace name 'IPowerBIClient' could not be found (are you missing a using directive or an assembly reference?)    PbiPaasWebApi   C:\SampleCode\pbi-web-api\PbiPaasWebApi\Controllers\ReportsController.cs    112 Active
Error   CS0246  The type or namespace name 'PowerBIClient' could not be found (are you missing a using directive or an assembly reference?) PbiPaasWebApi   C:\SampleCode\pbi-web-api\PbiPaasWebApi\Controllers\ReportsController.cs    116 Active
Error   CS0246  The type or namespace name 'PowerBIToken' could not be found (are you missing a using directive or an assembly reference?)  PbiPaasWebApi   C:\SampleCode\pbi-web-api\PbiPaasWebApi\Controllers\ReportsController.cs    112 Active
Error   CS0246  The type or namespace name 'Report' could not be found (are you missing a using directive or an assembly reference?)    PbiPaasWebApi   C:\SampleCode\pbi-web-api\PbiPaasWebApi\Models\ReportWithToken.cs   9   Active
Error   CS0246  The type or namespace name 'Report' could not be found (are you missing a using directive or an assembly reference?)    PbiPaasWebApi   C:\SampleCode\pbi-web-api\PbiPaasWebApi\Models\ReportWithToken.cs   13  Active

can't find these types anywhere...I've installed the latest (v1.1.1) powerbi packages from nuget

**Comment by mattmazzola** [comment]
I just re-cloned the latest master, updated the web.config and it built and embedded the report correctly.

Re-open if you're still having problems.
